Start by importing Pytorch & check the version

In [1]:
import torch
torch.__version__

'2.3.1+cu121'

create **scalar** : A scalar is a single number = zero dimension tensor.

In [6]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


create **Vector** : A single dimension tensor contains many numbers.  
(count the number of square brackets on outside ([) to the number of dimensions)

In [7]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


create **Matrix**

In [8]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


create a **Tensor**

In [9]:
TENSOR = torch.tensor([[
    [1, 2, 3],
    [3, 6, 9],
    [2, 4, 5]
]])

print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


# Random tensors

In [11]:
random_tensor = torch.rand(size=(3, 4))
print(random_tensor, random_tensor.dtype)

tensor([[0.9402, 0.1569, 0.5942, 0.1506],
        [0.9440, 0.0686, 0.7032, 0.9793],
        [0.4350, 0.9686, 0.4779, 0.0861]]) torch.float32


In [13]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
print(random_image_size_tensor.shape, random_image_size_tensor.ndim)

torch.Size([224, 224, 3]) 3


## Zeros and ones

In [14]:
zeros = torch.zeros(size=(3, 4))
print(zeros, zeros.dtype)

ones = torch.ones(size=(3, 4))
print(ones, ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.float32


### Creating a range and tensors like  

In [15]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecate = torch.range(0, 10)

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
print(zero_to_ten)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


C:\Users\zero\AppData\Local\Temp\ipykernel_18688\4036944844.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecate = torch.range(0, 10)


Tensors of all zeros with the same shape as a previous tensor

In [16]:
ten_zeros = torch.zeros_like(zero_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

In [17]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,          # defaults to None
                               device=None,         # defaults to None
                               requires_grad=False) # # if True, operations performed on the tensor are recorded

print(float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device)

torch.Size([3]) torch.float32 cpu


In [19]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

print(float_16_tensor)
print()

some_tensor = torch.rand(size=(3, 4))
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # default to CPU

tensor([3., 6., 9.], dtype=torch.float16)

tensor([[0.2891, 0.1224, 0.2402, 0.3944],
        [0.1112, 0.7239, 0.7351, 0.9009],
        [0.0552, 0.7970, 0.5786, 0.1741]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors (tensor operations)

In [22]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 10)
print(tensor)
tensor = tensor - 10
tensor = tensor + 10
print(tensor)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([1, 2, 3])
tensor([1, 2, 3])


Pytorch built-in functions

In [23]:
print(torch.multiply(tensor, 10))
print(torch.mul(tensor, 10))
print(tensor)

tensor([10, 20, 30])
tensor([10, 20, 30])
tensor([1, 2, 3])


In [24]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication

In [25]:
tensor = torch.tensor([1, 2, 3])
print(tensor.shape)
print()

print(tensor * tensor)
print(torch.matmul(tensor, tensor))
print(tensor @ tensor)


torch.Size([3])

tensor([1, 4, 9])
tensor(14)
tensor(14)


Do matrix multiplication by hand (not recommended). Use `torch.matmul()` is faster

In [27]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [28]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning (shape errors)

In [29]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=torch.float32)

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [31]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


#### play around with a linear layer

In [32]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,     # in_features = matches inner dimension of input 
                         out_features=6)    # out_features = describes outer value 

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape} \n")
print(f"Output: \n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2]) 

Output: 
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


#### Finding the min, max, mean, sum, etc (aggregation)

In [33]:
# Create a tensor
x = torch.arange(start=0, end=100, step=10)
print(x)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [34]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

Positional min/max

In [35]:
# Create a tensor
tensor = torch.arange(start=10, end=100, step=10)
print(f"Tensor: {tensor}")

# Return index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")


Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


Change tensor datatype

In [37]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

tensor_float16 = tensor.type(torch.float16)
print(tensor_float16)

tensor_int8 = tensor_float16.type(torch.int8)
print(tensor_int8)

torch.float32
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


#### Reshaping, stacking, squeezing, and unsqueezing

In [14]:
import torch
x = torch.arange(1., 8.)
print(x, x.shape)

x_reshaped = x.reshape((1, 7))
print(x_reshaped, x_reshaped.shape)

tensor([1., 2., 3., 4., 5., 6., 7.]) torch.Size([7])
tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])


`torch.view()` can also change the view  
**Change** the view changes the original tensor too.  
It only creates a new view of the same tensor

In [9]:
z = x.view(1, 7)
print(z, z.shape)

# Changing z changes x
z[:, 0] = 5
print(z, x)

tensor([[5., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])
tensor([[5., 2., 3., 4., 5., 6., 7.]]) tensor([[5., 2., 3., 4., 5., 6., 7.]])


stack new tensor on top

In [13]:
x_stacked = torch.stack([x, x, x, x], dim=0)
print(x_stacked)

tensor([[[5., 2., 3., 4., 5., 6., 7.]],

        [[5., 2., 3., 4., 5., 6., 7.]],

        [[5., 2., 3., 4., 5., 6., 7.]],

        [[5., 2., 3., 4., 5., 6., 7.]]])


Squeeze & unsqueeze

In [15]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous tensor: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [16]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [17]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


#### Indexing (selecting data from tensors)

In [18]:
x = torch.arange(start=1, end=10).reshape(1, 3, 3)
print(x, x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [19]:
print(f"First square bracket: \n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")


First square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [20]:
print(x[:, 0])
print(x[:, :, 1])
print(x[:, 1, 1])
print(x[0, 0, :])

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


### Pytorch tensors & Numpy

In [23]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
print(array, "\n" ,tensor)

# By default if you convert it to a tensor will created the datatype float64

[1. 2. 3. 4. 5. 6. 7.] 
 tensor([1., 2., 3., 4., 5., 6., 7.])


In [24]:
# Change the array, keep the tensor
array = array + 1
print(array, tensor)

[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.])


change the tensor to Numpy

In [27]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (take the random out of random)

In [28]:
import torch

random_tensor_A = torch.rand((3, 4))
random_tensor_B = torch.rand((3, 4))

print(f"Tensor A: \n{random_tensor_A}\n")
print(f"Tensor B: \n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (any where)")
random_tensor_A == random_tensor_B

Tensor A: 
tensor([[0.8195, 0.4871, 0.3970, 0.7673],
        [0.0963, 0.1115, 0.8758, 0.9564],
        [0.2639, 0.7822, 0.8879, 0.0375]])

Tensor B: 
tensor([[0.8572, 0.2094, 0.4702, 0.2779],
        [0.6819, 0.7703, 0.2650, 0.5895],
        [0.4060, 0.5557, 0.8787, 0.7832]])

Does Tensor A equal Tensor B? (any where)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
import torch

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand((3, 4))

# Have to reset the seed every time a new rand() is called, OR tensor_D would be different to tensor_C
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand((3, 4))

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

#### Running tensors on GPUs

In [30]:
import torch
print(torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
print(torch.cuda.device_count())

True
cuda
1


In [31]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')


Moving tensors back to the CPU

In [32]:
# If tensor is on GPU, can't transform it to Numpy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [33]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

[1 2 3]
