# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand((7, 7))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
tensor_B = torch.rand((1, 7)).transpose(1, 0)
# Perform matrix multiplication 
results = torch.mm(tensor_A, tensor_B)
results,results.shape

(tensor([[1.1964],
         [1.5557],
         [1.6188],
         [1.1734],
         [1.3292],
         [1.4078],
         [1.0189]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_a = torch.rand((7, 7))
tensor_b = torch.rand((1, 7)).permute(1, 0)

# Matrix multiply tensors
results = torch.mm(tensor_a, tensor_b)
results, results.shape

(tensor([[1.3299],
         [1.8111],
         [1.3228],
         [0.9725],
         [1.8285],
         [1.4806],
         [2.0489]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
torch.manual_seed(0)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
random_tensor_A = torch.rand((2, 3)).to(device)
random_tensor_B = torch.rand((2, 3)).to(device)

random_tensor_A, random_tensor_B

Device: cuda


(tensor([[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341]], device='cuda:0'),
 tensor([[0.4901, 0.8964, 0.4556],
         [0.6323, 0.3489, 0.4017]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
results = torch.mm(random_tensor_A, random_tensor_B.T)
results, results.shape

(tensor([[0.9722, 0.6174],
         [0.6292, 0.4455]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
max = torch.max(results)
# Find min
min = torch.min(results)

max, min

(tensor(0.9722, device='cuda:0'), tensor(0.4455, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
max_idx = torch.argmax(results)

# Find arg min
min_idx = torch.argmin(results)

max_idx, min_idx

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(0)

# Create random tensor
tensor = torch.rand((1, 1, 1, 10))
tensor_squeeze = torch.squeeze(tensor)

print(tensor, tensor.shape)
print(tensor_squeeze, tensor_squeeze.shape)


tensor([[[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
           0.4556, 0.6323]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
        0.6323]) torch.Size([10])
