### Tensors

In [2]:
import torch
import numpy as np

#### Initializing A Tensor

In [2]:
# Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
# From a Numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
# From another tensor
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n{x_ones}\n")

x_rand = torch.rand_like(x_ones, dtype=torch.float)
print(f"Random Tensor: \n{x_rand}\n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.1308, 0.0307],
        [0.9406, 0.9136]])



In [7]:
# With random or constant values
shape = (2, 3, )

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor}")
print(f"Ones Tensor: \n{ones_tensor}")
print(f"Zeros Tensor: \n{zeros_tensor}")

Random Tensor: 
tensor([[0.2536, 0.5812, 0.2353],
        [0.5091, 0.0852, 0.6373]])
Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Attributes of a Tensor

In [8]:
tensor = torch.rand((3, 4))
print(f"Shape of tensor: {tensor.shape}")
print(f"DataType of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
DataType of tensor: torch.float32
Device of tensor: cpu


#### Operations on Tensors

In [9]:
# We move out tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [3]:
tensor = torch.ones((4, 4))
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")

# torch.ones((3, 4, 5)) => tensor[..., -1] = tensor[:, :, -1]
print(f"Last column: {tensor[..., -1]}")

tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [13]:
# Arithmetic operations

y1 = tensor @ tensor.T
y2 = torch.mm(tensor, tensor.T)

y3 = torch.rand_like(y1)
torch.mm(tensor, tensor.T, out=y3)
print(y3)

# element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [14]:
# Single-element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [5]:
# in-place operations
print(f"{tensor} \n")
tensor.add(5)
print(tensor)

tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


#### Bridge with Numpy

In [6]:
# Tensor to numpy
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [7]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [8]:
# Numpy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)

print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [9]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
